In [1]:
import pandas as pd
import numpy as np
import random
from scipy.stats import norm
from datetime import datetime
import requests
from urllib.request import urlopen
from bs4 import BeautifulSoup

pd.set_option('max_columns', None)
pd.set_option('max_rows', None)

In [3]:
boxscores_url = 'https://stats.wnba.com/teams/boxscores-traditional/'
html_boxscores = urlopen(boxscores_url)
soup_boxscores = BeautifulSoup(html_boxscores)
soup_boxscores.find_all('tr')
headers_boxscores = [th.getText() for th in soup_boxscores.find_all('tr')[0].find_all('th')]
headers_boxscores = headers_boxscores[0:]
rows_boxscores = soup_boxscores.find_all('tr')[0:]
boxscore_results = [[td.getText() for td in rows_boxscores[i].find_all(['td','th'])] for i in range(len(rows_oct))]
boxscores = pd.DataFrame(boxscore_results, columns=headers_boxscores)
# boxscores = boxscores.drop([0])
# oct_sched['PTS'] = oct_sched['PTS'].astype(int)

IndexError: list index out of range

In [10]:
df = pd.read_excel('WNBA_Excel_Model.xlsx', sheet_name='Sched17')

df2 = pd.DataFrame()
df2[['Date','Playoff/Regular','Home Team', 'MP_1','FG_2', 'FGA_3','3P_4','3PA_5','FT_6','FTA_7','ORB_8','TRB_9','AST_10','STL_11','BLK_12','TOV_13','PF_14','PTS_15','ORtg_16','DRtg_17','Away Team', 'MP', 'FG', 'FGA','3P','3PA','FT','FTA','ORB','TRB','AST','STL','BLK','TOV','PF','PTS','ORtg','DRtg','POSS','PACE']] = df[['Date','Playoff/Regular','Away Team', 'MP', 'FG', 'FGA','3P','3PA','FT','FTA','ORB','TRB','AST','STL','BLK','TOV','PF','PTS','ORtg','DRtg','Home Team', 'MP_1','FG_2', 'FGA_3','3P_4','3PA_5','FT_6','FTA_7','ORB_8','TRB_9','AST_10','STL_11','BLK_12','TOV_13','PF_14','PTS_15','ORtg_16','DRtg_17','POSS','PACE']]

df = df.append(df2)

#df = df.loc[df['Date'] > datetime.strptime('Jun 20 2016', '%b %d %Y')]

teamStats = pd.DataFrame()
df['W'] = np.where(df['PTS'] > df['PTS_15'] , 1, 0)
teamStats = df.groupby('Away Team').sum()
teamStats['GP'] = df.groupby('Away Team').size()
teamStats['W'] = df.groupby('Away Team')['W'].sum()
teamStats['L'] = teamStats['GP'] - teamStats['W']
teamStats['POSS_std'] = df.groupby('Away Team')['POSS'].std()

teamStats = teamStats.rename(columns = {'MP_1':'O_MP', 'FG_2':'O_FG', 'FGA_3':'O_FGA', '3P_4':'O_3P', '3PA_5':'O_3PA', 'FT_6':'O_FT', 'FTA_7':'O_FTA', 'ORB_8':'O_ORB', 'TRB_9':'O_TRB', 'AST_10':'O_AST', 'STL_11':'O_STL', 'BLK_12':'O_BLK', 'TOV_13':'O_TOV', 'PF_14':'O_PF', 'PTS_15':'O_PTS', 'ORtg_16':'O_ORtg', 'DRtg_17':'O_DRtg'})

#teamStats['ORtg'] = teamStats['PTS'] * 100 / teamStats['POSS']
#teamStats
teamStats
# teamStats.columns = [] # Put columns in whatever order you need
# print(teamStats['POSS_std'])

,MP,FG,FGA,3P,3PA,FT,FTA,ORB,TRB,AST,STL,BLK,TOV,PF,PTS,ORtg,DRtg,O_MP,O_FG,O_FGA,O_3P,O_3PA,O_FT,O_FTA,O_ORB,O_TRB,O_AST,O_STL,O_BLK,O_TOV,O_PF,O_PTS,O_ORtg,O_DRtg,POSS,PACE,W,GP,L,POSS_std
Away Team,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Atlanta Dream,6940,988,2412,153,532,556,729,343,1194,599,235,155,414,663,2685,3361.902556,3528.104603,6940,1014,2314,191,608,592,740,298,1228,650,237,177,466,674,2811,3528.104603,3361.902556,2710.659855,2659.917199,12,34,22,4.439958
Chicago Sky,6925,1098,2380,217,579,379,482,257,1148,718,195,190,516,653,2792,3439.418526,3650.741907,6925,1097,2519,203,624,569,726,365,1240,705,304,132,381,532,2966,3650.741907,3439.418526,2760.343236,2712.222844,12,34,22,5.251330
Connecticut Sun,7000,1130,2520,227,627,520,705,347,1291,616,265,100,414,665,3007,3757.771226,3579.871544,7000,1051,2408,218,630,542,674,269,1178,588,230,135,449,665,2862,3579.871544,3757.771226,2803.407316,2803.407316,21,35,14,4.079422
Dallas Wings,7100,1006,2490,229,732,764,927,388,1213,547,285,132,447,708,3005,3723.687313,3840.121862,7100,1146,2394,191,553,622,777,318,1231,684,252,181,488,766,3105,3840.121862,3723.687313,2826.903027,2787.379741,16,35,19,5.549768
Indiana Fever,6850,960,2238,154,499,478,568,244,959,511,223,104,428,646,2552,3365.226015,3778.213905,6850,1034,2186,209,534,588,714,299,1196,602,225,111,454,620,2865,3778.213905,3365.226015,2581.126413,2562.601348,9,34,25,3.821024
Las Vegas Aces,6850,956,2230,162,486,455,592,314,1132,594,229,103,497,650,2529,3330.530573,3637.695026,6850,1019,2256,194,597,534,680,296,1117,679,266,163,414,561,2766,3637.695026,3330.530573,2586.503128,2567.823584,8,34,26,3.462267
Los Angeles Sparks,8490,1314,2776,217,668,622,757,283,1318,785,398,148,506,723,3467,4506.151760,4111.014010,8490,1172,2705,249,728,572,731,360,1362,720,265,139,650,773,3165,4111.014010,4506.151760,3230.370907,3198.909496,31,42,11,4.152922
Minnesota Lynx,8400,1359,2839,249,660,593,768,400,1489,844,330,164,561,695,3560,4619.201358,4066.367940,8400,1187,2798,233,745,524,657,343,1272,703,314,139,592,794,3131,4066.367940,4619.201358,3234.452593,3234.452593,33,42,9,4.296905
New York Liberty,7025,1025,2410,200,601,528,677,368,1349,582,211,135,436,687,2778,3626.202441,3502.080974,7025,961,2359,214,644,550,688,270,1118,547,224,133,383,622,2686,3502.080974,3626.202441,2681.267231,2671.637841,22,35,13,3.875999
Phoenix Mercury,7875,1105,2511,262,744,704,887,290,1245,681,241,168,522,837,3176,4051.578312,4077.552747,7875,1167,2653,204,658,654,828,346,1344,630,279,130,500,842,3192,4077.552747,4051.578312,3054.795991,3024.692407,20,39,19,4.513086
Seattle Storm,7075,1047,2231,253,701,530,654,224,1085,698,228,112,470,637,2877,3735.963586,3748.787253,7075,1067,2417,236,661,517,644,348,1203,574,258,118,428,667,2887,3748.787253,3735.963586,2693.612829,2665.491366,15,35,20,4.013841
Washington Mystics,7850,1115,2687,270,835,681,813,414,1414,635,235,182,424,710,3181,4181.451168,4178.533064,7850,1188,2715,251,682,546,700,360,1348,728,221,135,430,758,3173,4178.533064,4181.451168,2965.472812,2946.795192,20,39,19,3.946436

In [ ]:
numSims = 50000

data = pd.read_excel('Test.xlsx', sheet_name='TeamStats')

data = data[['TEAM', 'POSS', 'STD_POSS', 'ORtg/POSS', 'DRtg/POSS', 'STD_ORtg', 'STD_DRtg']]

home_team = input('Enter the name of the home team: ')
away_team = input('Enter the name of the away team: ')

home_data = data.loc[data['TEAM'] == home_team]
away_data = data.loc[data['TEAM'] == away_team]
league_data = data.loc[data['TEAM'] == 'LEAGUE AVERAGE']

normPoss = (home_data.iloc[0]['POSS'] + away_data.iloc[0]['POSS'] + league_data.iloc[0]['POSS']) / 3
normStdPoss = (home_data.iloc[0]['STD_POSS'] + away_data.iloc[0]['STD_POSS'] + league_data.iloc[0]['STD_POSS']) / 3

possessions = []
for i in range(numSims):
    r = random.uniform(0,1)
    x = norm.pdf(r, loc=normPoss, scale=normStdPoss)
    possesions.append(x)
    
Poss/G = sum(possessions/len(possessions))
Poss/G